load("//bazel:felicia_proto.bzl", "fel_proto_library")

fel_proto_library(
    name = "camera_message_proto",
    srcs = ["camera_message.proto"],
    visibility = ["//felicia/examples/learn/message_communication:internal"],
)
