py_library(
    name = "node_create_flag",
    srcs = ["node_create_flag.py"],
    visibility = ["//felicia/examples:internal"],
)

py_library(
    name = "import_order_resolver",
    srcs = ["import_order_resolver.py"],
    visibility = ["//felicia/examples:internal"],
)

py_library(
    name = "camera_flag",
    srcs = ["camera_flag.py"],
    visibility = ["//felicia/examples:internal"],
    deps = [":node_create_flag"],
)
