py_library(
    name = "node_create_flag",
    srcs = ["node_create_flag.py"],
    visibility = ["//felicia/examples/learn/message_communication:internal"],
)

py_library(
    name = "import_order_resolver",
    srcs = ["import_order_resolver.py"],
    visibility = ["//felicia/examples/learn/message_communication:internal"],
)
