package(default_visibility = ["//felicia:internal"])

load("//felicia/python:pybind.bzl", "py_bind_library")

py_bind_library(
    name = "status",
    cc_deps = [
        "//felicia/core:lib",
    ],
)
