package(default_visibility = ["//felicia:internal"])

load("//felicia/python:pybind.bzl", "fel_pybind_py_library")

fel_pybind_py_library(
    name = "status",
    cc_deps = [
        "//felicia/core:lib",
    ],
)
