load("//bazel:felicia_ros.bzl", "fel_ros_msg_library")

fel_ros_msg_library(
    name = "simple_message_ros_msg",
    srcs = [
        "SimpleMessage.msg",
    ],
    package = "felicia",
    visibility = ["//felicia/examples:internal"],
)
