load("//bazel:felicia_cc.bzl", "fel_cc_library")

fel_cc_library(
    name = "service_create_flag",
    srcs = ["service_create_flag.cc"],
    hdrs = ["service_create_flag.h"],
    visibility = ["//felicia/examples:internal"],
    deps = ["//felicia/examples/learn/common/cc:node_create_flag"],
)
