load("@env//:env.bzl", "FELICIA_ROOT", "TRAVIS")

def _felicia_env_impl(ctx):
    output = ctx.outputs.out
    ctx.actions.write(output = output, content =
                                           "// Generated by lib/lib.bzl\n" +
                                           "#ifndef FELICIA_CORE_LIB_BASE_FELICIA_ENV_H_\n" +
                                           "#define FELICIA_CORE_LIB_BASE_FELICIA_ENV_H_\n\n" +
                                           "#include \"third_party/chromium/base/files/file_path.h\"\n" +
                                           "#include \"third_party/chromium/build/buildflag.h\"\n\n" +
                                           "#define FELICIA_ROOT \"%s\"\n" % (FELICIA_ROOT) +
                                           "#define FELICIA_RELATIVE_PATH(x) FILE_PATH_LITERAL(\"\") FELICIA_ROOT x\n" +
                                           "#define BUILDFLAG_INTERNAL_TRAVIS() %s\n\n" % (TRAVIS.lower()) +
                                           "#endif  // FELICIA_CORE_LIB_BASE_FELICIA_ENV_H_")

felicia_env = rule(
    implementation = _felicia_env_impl,
    outputs = {"out": "%{name}.h"},
)
