py_library(
    name = "service_create_flag",
    srcs = ["service_create_flag.py"],
    visibility = ["//felicia/examples:internal"],
    deps = ["//felicia/examples/learn/common/python:node_create_flag"],
)
