package(default_visibility = ["//visibility:private"])

py_binary(
    name = "node_creator",
    main = "node_creator.py",
    srcs = ["node_creator.py"],
    deps = [
        "//felicia/python/util/command_line_interface:command_line_util",
    ],
)
