load("//bazel:felicia_nodejs_bind.bzl", "fel_nodejs_bind_node_library")

fel_nodejs_bind_node_library(
    name = "typed_call",
    srcs = [
        "typed_call_test.cc",
    ],
    deps = [
        "//felicia/core/lib",
        "//felicia/js:typed_call",
    ],
)
