# Copyright (c) 2019 The Felicia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

exports_files([
    "ros/msg.h.template",
    "ros/srv.h.template",
    "ros_msg_gen.py",
])
