# Copyright (c) 2019 The Felicia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("//bazel:felicia_nodejs_bind.bzl", "fel_nodejs_bind_node_library")

fel_nodejs_bind_node_library(
    name = "typed_call_unittests",
    srcs = ["typed_call_unittest.cc"],
    deps = [
        "//felicia/core/lib",
        "//felicia/js/type_conversion",
    ],
)
